### ISSUE TITLE
LogLevel doesn't work when using isolatedModules

### ISSUE THREAD

**Issue by stephenh** [graphile/logger#1]
### Summary

Because `LogLevel` is a const enum, TypeScript when running with `isolatedModules` doesn't know the values to inline.

### Steps to reproduce

Create a new TS project that has `isolatedModules: true` in its `tsconfig` and try to import `LogLevel`, you'll get a compile error. 

And if you try to `ts-ignore` the error, then `LogLevel.ERROR` ends up being `undefined.ERROR` at runtime, b/c the import doesn't work (because the `LogLevel` symbol doesn't actually exist at runtime), and `undefined.ERROR` will cause an exception.

### Possible Solution

For now we're just hard-coding the `LogLevel` values, i.e.:

```typescript
    // Use pino for JSON logging
    // https://github.com/graphile/logger#creating-a-custom-logger
    logger: new GraphileLogger((scope) => {
      const scopedLogger = logger.child(scope);
      return (level, message, meta = {}) => {
        switch (level) {
          case "error":
            return scopedLogger.error(meta, message);
          case "warning":
            return scopedLogger.warn(meta, message);
          case "debug":
            return scopedLogger.debug(meta, message);
          case "info":
          default:
            return scopedLogger.info(meta, message);
        }
      };
```

De-`const`-izing `LogLevel` would fix the issue.

**Comment by benjie** [comment]
I hate TypeScript enums so much.

**Comment by benjie** [comment]
I've just stopped suggesting you import LogLevel; seems the easiest fix :man_shrugging:

**Comment by stephenh** [comment]
Yeah, sounds good. Makes me wonder if just using a type literal like `type LogLevel = "error" | "warning" | ...` would be "better", but then `LogLevel.ERROR` wouldn't work w/o using a slightly different prefix like `LogLevels.ERROR` or something. :shrug:

**Comment by benjie** [comment]
Yeah. I decided a while ago I'm basically never going to use a TypeScript enum ever again. I also dislike Postgres enums... I'm starting to wonder if I just hate enums in general TBH... :laughing: 

But yes, in all my newer code I'm using constant string unions rather than enums, seems to be working well so far.
