### ISSUE TITLE
Enum isn't exported correctly for use in another TypeScript project.

### ISSUE THREAD

**Issue by ps2goat** [graphile/logger#3]
### Summary
`export const enum LogLevel` means that the enum will not work as expected with TypeScript. This needs to be `export enum LogLevel` instead.

### Steps to reproduce
Create a new TypeScript project, add & import @graphile/logger. Try to use it like `myVal === LogLevel.WARNING` and you should get an error about can't read property of undefined. We have a wrapper that is using the log level as a condition for how it maps to our internal logger.

This occurs only at run time.

### Expected results
enum should not be const, values are able to be used and match their expected string values from the `@graphile/logger` package.

### Actual results
It throws an error that it can’t read the property

### Additional context

https://ncjamieson.com/dont-export-const-enums/

### Possible Solution
use `export enum LogLevel` instead.

**Comment by benjie** [comment]
Use `myVal === 'warning'` instead.

TypeScript enums are hideous; I was hoping to avoid the worst parts by using a `const enum` but I was naïve and idealistic; I should have just done `type LogLevel = 'debug' | 'info' | 'warning' | 'error';`, which is what future versions of this project will use.
